### ISSUE TITLE
Version `1.3.3` does not provides types

### ISSUE THREAD

**Issue by jorg-vr** [alexmojaki/pyodide-worker-runner#32]
Version `1.3.3` does not provide types, making it harder to use in a typescript project.

Everything still works in version `1.3.1`

If this was intentional, it should probably have been a major version bump as it is a breaking change to remove this info.

Context: I am bringing Papyros up to date: https://github.com/dodona-edu/papyros/pull/557

**Comment by alexmojaki** [comment]
No, that wasn't intentional, and I hadn't noticed. Making these libraries for Papyros was my first and only time publishing JS libraries, I still don't really understand how package.json/tsconfig.json/webpack.config.js work. If you can figure out the correct config that'd be great.
