### ISSUE TITLE
Typing mismatch

### ISSUE THREAD

**Issue by winniederidder** [alexmojaki/pyodide-worker-runner#5]
When using both comsync and pyodide-worker-runner, it is not possible to assign a value of PyodideClient to a variable of type SyncClient with the following error:
`
Type 'PyodideClient<any>' is not assignable to type 'SyncClient<any>'.   Types have separate declarations of a private property '_interruptRejector'.
`
I believe this is caused due to a dependency mismatch, as pyodide-worker-runner uses a currently outdated version of comsync (0.0.6 instead of 0.0.7). Updating this should be enough. If not, the private fields should be made protected, but I doubt this will be required.

**Comment by alexmojaki** [comment]
Ugh, JS dependencies feel like a mess to me and I don't know how best to deal with them. What do you think of making comsync a peer dependency of pyodide-worker-runner? sync-message and comlink are already peer dependencies of comsync.

**Comment by winniederidder** [comment]
If that makes keeping all verions up to date with each other smoother, then I am okay with that. I haven't really dug into peerDependencies myself, so I can't ensure it's the best way to go. In this specific case, a simple dependency update will also solve the issue.

**Comment by alexmojaki** [comment]
Yes, but then pyodide-worker-runner must be updated every time comsync is updated, and what if you want to use an older version of comsync?

**Comment by winniederidder** [comment]
Then it is probably best to make it a peerDependency.
