### ISSUE TITLE
Pyodide 0.20.0

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/pyodide-worker-runner#8]
Pyodide 0.20.0 has released and this package should be updated accordingly.

Notable changes from https://pyodide.org/en/stable/project/changelog.html:

- The extractDir argument to [unpackArchive](https://pyodide.org/en/stable/usage/api/js-api.html#pyodide.unpackArchive) is now passed as a named argument. The old usage still works with a deprecation warning. `loadPyodideAndPackage` will need updating.
- It is no longer necessary to provide indexURL to [loadPyodide](https://pyodide.org/en/stable/usage/api/js-api.html#globalThis.loadPyodide). This means `defaultPyodideLoader` can be slightly cleaner.
- The Javascript package was migrated to Typescript. Hopefully that means the original issue in #1 can be resolved with the official types as I suggested.
- Pyodide now runs Python 3.10.2. That doesn't actually affect this package but it's potentially significant anyway for futurecoder etc.

Obviously `defaultPyodideLoader` should also update the default version to `0.20.0`.

Beyond that, I'd like the pyodide npm package to be a dependency of this package. The CDN would still be used for the big stuff, but the bootstrap loader would be bundled to avoid an extra request.

@winniederidder what do you think?

**Comment by winniederidder** [comment]
Sounds good to me!

**Comment by winniederidder** [comment]
Just to be clear, is this something you plan to do yourself or are you awaiting a PR?

**Comment by alexmojaki** [comment]
I might do it, but I'm less focused on futurecoder these days, so don't hold your breath. If you want these changes soon, making a PR would be best, and of course I'd appreciate that.

**Comment by alexmojaki** [comment]
I can't use the npm package because of the Pyodide issue linked above.

Interrupts seem to have regressed in 0.20.0 (https://github.com/pyodide/pyodide/issues/2400) so actually I don't think upgrading is a good idea and I don't think I'll merge the PR.

**Comment by winniederidder** [comment]
@alexmojaki The related issue on Pyodide has been closed, will we upgrade to the next version?

**Comment by alexmojaki** [comment]
I think this package should wait until the next stable release before changing anything, yes.

In the meantime you should still be able to set the version to 0.20.0. But I don't know of any significant benefits that will come from it.

An alpha version was released and I tried using it as an npm dependency, see https://github.com/pyodide/pyodide/issues/2403#issuecomment-1114731607

**Comment by alexmojaki** [comment]
Deployed to futurecoder: https://github.com/alexmojaki/futurecoder/pull/376
